apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ekswatch-operator.fullname" . }}-ui
  labels:
    control-plane: ui
  {{- include "ekswatch-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      control-plane: ui
  template:
    metadata:
      labels:
        control-plane: ui
      {{- include "ekswatch-operator.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ekswatch-operator.fullname" . }}-ui
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      containers:
        - name: ui
          image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          command: ["/ui"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.ui.containerSecurityContext | nindent 12 }}