apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ekswatch-operator.fullname" . }}-aws-secret
  labels:
  {{- include "ekswatch-operator.labels" . | nindent 4 }}
data:
  accessKeyId: {{ required "awsSecret.accessKeyId is required" .Values.awsSecret.accessKeyId
    | b64enc | quote }}
  pat: {{ required "awsSecret.pat is required" .Values.awsSecret.pat | b64enc | quote
    }}
  secretAccessKey: {{ required "awsSecret.secretAccessKey is required" .Values.awsSecret.secretAccessKey
    | b64enc | quote }}
type: Opaque
