apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  labels:
  {{- include "ekswatch-operator.labels" . | nindent 4 }}
data:
  accessKeyId: blah
  pat: blah
  secretAccessKey: blah
type: Opaque
