apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ekswatch-operator.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "ekswatch-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "ekswatch-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "ekswatch-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args: {{- toYaml .Values.controllerManager.manager.args | nindent 8 }}
        command:
        - /manager
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: accessKeyId
              name: aws-secret
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: secretAccessKey
              name: aws-secret
        - name: PAT
          valueFrom:
            secretKeyRef:
              key: pat
              name: aws-secret
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.controllerManager.manager.containerSecurityContext
          | nindent 10 }}
      securityContext: {{- toYaml .Values.controllerManager.podSecurityContext | nindent
        8 }}
      serviceAccountName: {{ include "ekswatch-operator.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ekswatch-operator.fullname" . }}-ui
  labels:
    control-plane: ui
  {{- include "ekswatch-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      control-plane: ui
    {{- include "ekswatch-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: ui
      {{- include "ekswatch-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: ui
    spec:
      containers:
      - command:
        - /ui
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.ui.ui.image.repository }}:{{ .Values.ui.ui.image.tag | default
          .Chart.AppVersion }}
        name: ui
        resources: {{- toYaml .Values.ui.ui.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.ui.ui.containerSecurityContext | nindent 10
          }}
      securityContext: {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      serviceAccountName: ui
      terminationGracePeriodSeconds: 10
