# permissions for end users to view ekswatches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ekswatch-operator
    app.kubernetes.io/managed-by: kustomize
  name: ekswatch-viewer-role
rules:
- apiGroups:
  - ekstools.devops.automation
  resources:
  - ekswatches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ekstools.devops.automation
  resources:
  - ekswatches/status
  verbs:
  - get
