---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ekstools.devops.automation
  resources:
  - ekswatches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ekstools.devops.automation
  resources:
  - ekswatches/finalizers
  verbs:
  - update
- apiGroups:
  - ekstools.devops.automation
  resources:
  - ekswatches/status
  verbs:
  - get
  - patch
  - update
