name: Build Image Workflow
on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - Makefile
      - .github/workflows/build_image.yaml
      - api/**
      - cmd/**
      - internal/**


jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Produce and push docker image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          new_version=$(cat Makefile | grep "VERSION ?= " | cut -d'=' -f2 | tr -d ' ' | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)

          echo "New version: $new_version"
          
          sed -i "s/VERSION ?= .*/VERSION ?= $new_version/" Makefile

          make IMAGE_TAG_BASE=ghcr.io/${{ github.repository_owner }}/ekswatch-operator docker-buildx

          git config --global user.name "build-image-bot"
          git config --global user.email "a@b.c"
          git add .
          git commit -m "Produced and pushed new image: $new_version"
          git push origin HEAD:master


      - name: Set output
        id: version_setter
        run: echo "VERSION=${{ steps.build_image.outputs.new_version }}" >> $GITHUB_OUTPUT
          
  trigger_build_helm_chart:
    uses: maksimstankevic/ekswatch-operator/.github/workflows/build_helm_chart.yaml@master
    with:
      version: ${{ needs.build_image.outputs.VERSION }}
    needs: build_image
